spring.application.name=SpringSecurityService

server.port = 8082

spring.security.user.name=fita
spring.security.user.password=1234
server.servlet.session.cookie.same-site=strict

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/securitydemo
spring.datasource.username=securityUser
#spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true